# Generated by Django 5.0.4 on 2024-04-22 12:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WorkerGrade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salary', models.IntegerField(db_column='slary', default=0)),
                ('accessLevel', models.IntegerField(db_column='accessLevel', default=0)),
                ('gradeName', models.CharField(db_column='gradeName', default='No name', max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userName', models.CharField(db_column='userName', default='No name', max_length=128)),
                ('userSurname', models.CharField(db_column='userSurname', default='No surname', max_length=128)),
                ('userMiddleName', models.CharField(db_column='userMiddleName', default='No middlename', max_length=128)),
                ('creationDate', models.DateField(auto_now_add=True)),
                ('lastModified', models.DateField(auto_now=True)),
                ('WorkerGrade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.workergrade')),
            ],
        ),
    ]
