# Generated by Django 5.0.4 on 2024-04-24 09:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_gost'),
    ]

    operations = [
        migrations.CreateModel(
            name='GOST_DOCK',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idGOST', models.IntegerField(db_column='idGOST', null=True)),
                ('idDOCK', models.IntegerField(db_column='idDOCK', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Agreements',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creationDate', models.DateField(auto_now_add=True)),
                ('lastModified', models.DateField(auto_now=True)),
                ('result', models.BooleanField(default=False)),
                ('comment', models.CharField(db_column='comment', default='No comment', max_length=256)),
                ('commentOLD', models.CharField(db_column='commentOLD', default='No old comment', max_length=256)),
                ('dock', models.FileField(upload_to='Agreement')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='creator', to='api.user')),
                ('inspector', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inspector', to='api.user')),
            ],
        ),
        migrations.CreateModel(
            name='oldAgreement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creationDate', models.DateField(auto_now_add=True)),
                ('comment', models.CharField(db_column='comment', default='No comment', max_length=256)),
                ('commentOLD', models.CharField(db_column='commentOLD', default='No old comment', max_length=256)),
                ('idAgreement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.agreements')),
            ],
        ),
        migrations.CreateModel(
            name='TP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currentVersionTP', models.FileField(upload_to='TP')),
                ('creationDate', models.DateField(auto_now_add=True)),
                ('lastModified', models.DateField(auto_now=True)),
                ('needForChange', models.BooleanField(default=False)),
                ('comment', models.CharField(db_column='comment', default='No name', max_length=256)),
                ('newDockVersion', models.FileField(blank=True, null=True, upload_to='TP')),
                ('idCreator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.user')),
            ],
        ),
        migrations.CreateModel(
            name='oldTP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creationDate', models.DateField(auto_now_add=True)),
                ('dock', models.FileField(upload_to='TPold')),
                ('idTP', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.tp')),
            ],
        ),
        migrations.AddField(
            model_name='agreements',
            name='idTP',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.tp'),
        ),
        migrations.AlterUniqueTogether(
            name='agreements',
            unique_together={('creator', 'inspector')},
        ),
    ]
