# Generated by Django 5.0.4 on 2024-04-24 09:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_gost_dock_agreements_oldagreement_tp_oldtp_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agreements',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='creatorARG', to='api.user'),
        ),
        migrations.AlterField(
            model_name='agreements',
            name='inspector',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inspectorARG', to='api.user'),
        ),
    ]
