# Generated by Django 5.0.4 on 2024-04-24 09:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_agreements_creator_alter_agreements_inspector'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agreements',
            name='comment',
            field=models.CharField(db_column='comment', default='No comment', max_length=256, verbose_name='Комментарий'),
        ),
        migrations.AlterField(
            model_name='agreements',
            name='commentOLD',
            field=models.CharField(db_column='commentOLD', default='No old comment', max_length=256, verbose_name='Комментарий 2'),
        ),
        migrations.AlterField(
            model_name='agreements',
            name='creationDate',
            field=models.DateField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='agreements',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='creatorARG', to='api.user', verbose_name='id Создателя документа'),
        ),
        migrations.AlterField(
            model_name='agreements',
            name='dock',
            field=models.FileField(upload_to='Agreement', verbose_name='Документ для рассмотрения'),
        ),
        migrations.AlterField(
            model_name='agreements',
            name='idTP',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.tp', verbose_name='id ТП'),
        ),
        migrations.AlterField(
            model_name='agreements',
            name='inspector',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inspectorARG', to='api.user', verbose_name='id Согласующего'),
        ),
        migrations.AlterField(
            model_name='agreements',
            name='lastModified',
            field=models.DateField(auto_now=True, verbose_name='Дата последнего изменения'),
        ),
        migrations.AlterField(
            model_name='agreements',
            name='result',
            field=models.BooleanField(default=False, verbose_name='Результата согласования'),
        ),
        migrations.AlterField(
            model_name='gost',
            name='creationDate',
            field=models.DateField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='gost',
            name='file',
            field=models.FileField(upload_to='GOST', verbose_name='Файл ГОСТ'),
        ),
        migrations.AlterField(
            model_name='gost',
            name='gostName',
            field=models.CharField(db_column='GostName', default='No name', max_length=128, verbose_name='Наименование'),
        ),
        migrations.AlterField(
            model_name='gost',
            name='idCreator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.user', verbose_name='id Создателя'),
        ),
        migrations.AlterField(
            model_name='gost',
            name='lastModified',
            field=models.DateField(auto_now=True, verbose_name='Дата последнего изменения'),
        ),
        migrations.AlterField(
            model_name='gost_dock',
            name='idDOCK',
            field=models.IntegerField(db_column='idDOCK', null=True, verbose_name='id ТП'),
        ),
        migrations.AlterField(
            model_name='gost_dock',
            name='idGOST',
            field=models.IntegerField(db_column='idGOST', null=True, verbose_name='id ГОСТ'),
        ),
        migrations.AlterField(
            model_name='oldagreement',
            name='comment',
            field=models.CharField(db_column='comment', default='No comment', max_length=256, verbose_name='Комментарий'),
        ),
        migrations.AlterField(
            model_name='oldagreement',
            name='commentOLD',
            field=models.CharField(db_column='commentOLD', default='No old comment', max_length=256, verbose_name='Комментарий 2'),
        ),
        migrations.AlterField(
            model_name='oldagreement',
            name='creationDate',
            field=models.DateField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='oldagreement',
            name='idAgreement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.agreements', verbose_name='id согласования'),
        ),
        migrations.AlterField(
            model_name='oldtp',
            name='creationDate',
            field=models.DateField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='oldtp',
            name='dock',
            field=models.FileField(upload_to='TPold', verbose_name='ТП документ'),
        ),
        migrations.AlterField(
            model_name='oldtp',
            name='idTP',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.tp', verbose_name='id ТП'),
        ),
        migrations.AlterField(
            model_name='tp',
            name='comment',
            field=models.CharField(db_column='comment', default='No name', max_length=256, verbose_name='Комментарий'),
        ),
        migrations.AlterField(
            model_name='tp',
            name='creationDate',
            field=models.DateField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='tp',
            name='currentVersionTP',
            field=models.FileField(upload_to='TP', verbose_name='Текущая версия ТП'),
        ),
        migrations.AlterField(
            model_name='tp',
            name='idCreator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.user', verbose_name='id создателя'),
        ),
        migrations.AlterField(
            model_name='tp',
            name='lastModified',
            field=models.DateField(auto_now=True, verbose_name='Дата последнего изменения'),
        ),
        migrations.AlterField(
            model_name='tp',
            name='needForChange',
            field=models.BooleanField(default=False, verbose_name='Необходимость корректировки'),
        ),
        migrations.AlterField(
            model_name='tp',
            name='newDockVersion',
            field=models.FileField(blank=True, null=True, upload_to='TP', verbose_name='Несогласованная версия ТП'),
        ),
        migrations.AlterField(
            model_name='user',
            name='WorkerGrade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.workergrade', verbose_name='id должности'),
        ),
        migrations.AlterField(
            model_name='user',
            name='creationDate',
            field=models.DateField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='user',
            name='lastModified',
            field=models.DateField(auto_now=True, verbose_name='Дата последнего изменения'),
        ),
        migrations.AlterField(
            model_name='user',
            name='userMiddleName',
            field=models.CharField(db_column='userMiddleName', default='No middlename', max_length=128, verbose_name='Отчество'),
        ),
        migrations.AlterField(
            model_name='user',
            name='userName',
            field=models.CharField(db_column='userName', default='No name', max_length=128, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='user',
            name='userSurname',
            field=models.CharField(db_column='userSurname', default='No surname', max_length=128, verbose_name='Фамилия'),
        ),
        migrations.AlterField(
            model_name='workergrade',
            name='accessLevel',
            field=models.IntegerField(db_column='accessLevel', default=0, verbose_name='Уровень прав'),
        ),
        migrations.AlterField(
            model_name='workergrade',
            name='gradeName',
            field=models.CharField(db_column='gradeName', default='No name', max_length=128, verbose_name='Наименование должности'),
        ),
        migrations.AlterField(
            model_name='workergrade',
            name='salary',
            field=models.IntegerField(db_column='slary', default=0, verbose_name='Зарплата'),
        ),
    ]
