# Generated by Django 5.0.4 on 2024-04-24 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_rename_agreements_agreement'),
    ]

    operations = [
        migrations.AddField(
            model_name='tp',
            name='TpName',
            field=models.CharField(db_column='TpName', default='No name', max_length=128, verbose_name='Наименование ТП'),
        ),
    ]
