# Generated by Django 5.0.4 on 2024-04-24 10:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_tp_tpname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gost_dock',
            name='idDOCK',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.tp', verbose_name='id ТП'),
        ),
        migrations.AlterField(
            model_name='gost_dock',
            name='idGOST',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.gost', verbose_name='id ГОСТ'),
        ),
    ]
