# Generated by Django 5.0.4 on 2024-04-24 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_agreement_idactual'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agreement',
            name='idActual',
            field=models.BooleanField(default=True, verbose_name='Актуальность'),
        ),
    ]
