# Generated by Django 5.0.4 on 2024-04-24 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_tp_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tp',
            name='password',
        ),
        migrations.AddField(
            model_name='user',
            name='password',
            field=models.CharField(db_column='password', default='pass123', max_length=128, verbose_name='Пароль'),
        ),
    ]
