# Generated by Django 5.0.4 on 2024-05-13 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_remove_tp_password_user_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='login',
            field=models.CharField(db_column='Login', default='Login123', max_length=128, verbose_name='Логин'),
        ),
    ]
