# Generated by Django 5.0.4 on 2024-05-16 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_rename_idactual_agreement_isactual_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tp',
            name='idTpString',
        ),
    ]
