# Generated by Django 5.0.4 on 2024-05-16 19:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_alter_agreement_idtp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agreement',
            name='inspector',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inspectorARG', to='api.user', verbose_name='id Согласующего'),
        ),
    ]
