# Generated by Django 5.0.4 on 2024-05-16 19:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_alter_agreement_inspector'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='agreement',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='agreement',
            name='inspector',
        ),
    ]
