# Generated by Django 5.0.4 on 2024-05-16 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_alter_agreement_idtp'),
    ]

    operations = [
        migrations.AddField(
            model_name='agreement',
            name='NewName',
            field=models.CharField(db_column='NewName', max_length=256, null=True, verbose_name='Новое наименование'),
        ),
    ]
