# Generated by Django 5.0.4 on 2024-05-19 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_agreement_isnewtp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agreement',
            name='commentOLD',
            field=models.CharField(db_column='adminComment', default='No old comment', max_length=256, verbose_name='Причина отказа администратором'),
        ),
    ]
