# Generated by Django 5.0.4 on 2024-05-19 18:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_alter_agreement_commentold'),
    ]

    operations = [
        migrations.RenameField(
            model_name='agreement',
            old_name='commentOLD',
            new_name='AdminComment',
        ),
    ]
