# Generated by Django 5.0.4 on 2024-06-02 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_agreement_isuseraswercommnet'),
    ]

    operations = [
        migrations.AddField(
            model_name='gost',
            name='gostNameReal',
            field=models.CharField(db_column='GostNameReal', default='No name', max_length=128, verbose_name='Наименование реальное'),
        ),
    ]
